language: rust
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin -f
  fi

before_script: |
  if [[ "$TRAVIS_RUST_VERSION" != nightly ]]; then
    rustup component add clippy
  else
    rustup component add clippy --toolchain=nightly || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
  fi

script:
  - cargo clean
  - cargo build
  - cargo clippy
  - cargo test

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

    if [[ -n "$TOKEN" ]]; then
      cargo doc \
        && echo '<meta http-equiv=refresh content=0;url=packed_freelist/index.html>' > target/doc/index.html && \
        sudo pip install ghp-import && \
        ghp-import -n target/doc && \
        git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
    fi
  fi